### PR TITLE
(SIMP-4885) Add hash_to_opts function

### PR DESCRIPTION
**Pull request by jeefberkey**
- Add `simplib::hash_to_opts` which turns a hash into a string with each
  key prefixed with '--' and connected to each value with '='. Useful
  for generating commands

SIMP-4885 #close

### CODE REVIEW

**Comment by jeefberkey** [comment]
:clock4: https://gitlab.com/simp/pupmod-simp-simplib/pipelines/21482609

**Comment by jeefberkey** [comment]
> Short => Sort option -q and joined to the value with a space

What do you mean by this? 

I agree with the first point.

**Comment by trevor-vaughan** [comment]
@jeefberkey The Short comment is due to the following:

`--foo=bar` is usually equivalent to `-f bar`

**Comment by jeefberkey** [comment]
@trevor-vaughan that case is covered now, and tested.

**Pull request merged**
